name: Fast Auto Tag and Release (Testing)

on:
  # schedule:
  #   - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
          fetch-depth: 0

      - name: Increment version and update file
        run: |
          # Extract the current version from configure.ac
          VERSION=$(grep 'AC_INIT(\[tmux\],' configure.ac | sed -n 's/.*AC_INIT(\[tmux\], \([next-]*[0-9]*\.[0-9]*\)).*/\1/p')
          echo "Current version: $VERSION"

          # Increment the minor version
          IFS='.' read -ra VER <<< "$VERSION"
          NEW_MINOR=$((VER[1]+1))
          NEW_VERSION="${VER[0]}.$NEW_MINOR"

          # Write back to file
          sed -i "s/AC_INIT(\[tmux\], $VERSION)/AC_INIT([tmux], $NEW_VERSION)/" configure.ac

          # Set environment variable to use in subsequent steps
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add configure.ac
          git commit -m "Increment version to $NEW_VERSION"

      - name: Create tag
        run: |
          git tag -a "v0.1.11" -m "Release v$NEW_VERSION"
          git push origin "v0.1.11"
          git push
