name: Fast Auto Tag and Release (Testing)

on:
  # schedule:
  #   - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
          fetch-depth: 0

      - name: "Remove -next prefix from version in configure.ac"
        run: sed -i '/AC_INIT(\[tmux\], /s/next-//' configure.ac
      - name: "Extract version numer"
        run: |
          VERSION=$(grep 'AC_INIT(\[tmux\],' configure.ac | sed -n 's/.*AC_INIT(\[tmux\], \([0-9]*\.[0-9]*\.[0-9]*\)).*/\1/p')
          echo "Current version: $VERSION"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: "Update next version number"
        run: |
          IFS='.' read -ra VER <<< "$VERSION"
          NEW_PATCH=$((VER[2]+1))
          NEW_VERSION="${VER[0]}.${VER[1]}.$NEW_PATCH"

          # Write back to file
          sed -i "s/AC_INIT(\[tmux\], $VERSION)/AC_INIT([tmux], next-$NEW_VERSION)/" configure.ac
          git add configure.ac
          git commit -m "Bump version to next-$NEW_VERSION"
          git push origin HEAD
