name: "release"

on:
  release:
    types: [published]

jobs:
  edit_release:
    runs-on: ubuntu-latest

    steps:
      - name: Edit Release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          body: "Released to GitHub Packages."
