---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    runs-on: "ubuntu-latest"
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"
        with:
          lfs: true
          fetch-depth: 0

      - id: "yarn-cache"
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: "actions/cache@v2.1.6"
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      # - run: "yarn install --frozen-lockfile"
      # - run: "yarn lint"
      # - run: "yarn build"
      # - run: "yarn jest --env=node --colors --forceExit"

      # - run: "sh autogen.sh"
      # - run: "./configure"
      - run: "sudo apt-get update -qq"
      - run: "sudo apt-get -y install bison \
          autotools-dev \
          libncurses5-dev \
          libevent-dev \
          pkg-config \
          libutempter-dev \
          build-essential"
      - run: "sh .github/travis/before-install.sh"
      - run: "sh .github/travis/build.sh"
      - run: "make dist"

      - run: "LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)"
      - run: "primary_num=$(echo $LAST_TAG | sed 's/\..*//')"
      - run: "subnum=${LAST_TAG#*\.}"
      - run: "newsubnum=$(( $(echo $subnum | sed 's/[^0-9]*//g') + 1 ))"
      - run: "new_tag=$(echo $primary_num.$newsubnum)"

      - run: "git log --pretty=format:'%s' $LAST_TAG..HEAD > /tmp/tmux-tagged-release"
      - run: "sed 's/^/* /' /tmp/tmux-tagged-release"
      - run: "echo CHANGES FROM $LAST_TAG to $new_tag | cat - /tmp/tmux-tagged-release > /tmp/tmux-tagged-release"
      # add newlines
      - run: "sed G /tmp/tmux-tagged-release"
      - run: "cat /tmp/tmux-tagged-release | cat - CHANGES > CHANGES"
      - run: "rm /tmp/tmux-tagged-release"
      - run: "git commit -m 'change CHANGES for new release'"
      - run: "git push"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ new_tag }}"
          prerelease: false
          files: |
            *.tar.gz
        id: "automatic_releases"

      # marvinpinto/action-keybase-notifications
      # marvinpinto/action-automatic-releases
      # - name: "Automatically mirror release artifacts"
      #   env:
      #     GITHUB_SUPER_TOKEN: ${{ secrets.GITHUB_SUPER_TOKEN }}
      #   run: |
      #     ./scripts/mirror-actions.sh "$AUTOMATIC_RELEASES_TAG"

      # - uses: "marvinpinto/action-keybase-notifications@latest"
      #   if: always()
      #   with:
      #     job_status: ${{ job.status }}
      #     opensentinel_token: ${{ secrets.OSL_TOKEN }}
